In [1]:
import numpy as np

In [3]:
np.random.choice(10,4,replace = False)

array([3, 8, 6, 0])

In [6]:
subset = np.random.choice(10,8,replace = False)
subset.sort()
subset

array([0, 1, 2, 3, 4, 6, 7, 9])

In [7]:
np.random.choice(subset,4,replace = False)

array([1, 7, 2, 6])

In [8]:
a = "12"
a+="1"
a

'121'

In [ ]:
class base:
    def __init__(self, limit = None):
        self.n_class = 10
        if limit:
            self.n_class = limit

class second(base):
    def __init__(self, limit=None):
        super().__init__(limit)

In [2]:
pwd

'/srv/home/zxu444/few_shot_image/notebook'

In [3]:
cd ..

/srv/home/zxu444/few_shot_image


In [1]:

import torch
import torch.nn as nn
import torch.nn.functional as F
import numpy as np
from tqdm import tqdm
from torch.utils.data import DataLoader
# from tensorboardX import SummaryWriter
from torch.utils.tensorboard import SummaryWriter


In [2]:
import sys
sys.path.insert(0, '/srv/home/zxu444/few_shot_image')

In [3]:
import datasets

In [4]:
datasets

<module 'datasets' from '/srv/home/zxu444/few_shot_image/datasets/__init__.py'>

In [5]:
datasets.datasets

{'mini-imagenet': datasets.mini_imagenet.MiniImageNet,
 'meta-mini-imagenet': datasets.mini_imagenet.MetaMiniImageNet,
 'unsup-meta-mini-imagenet': datasets.mini_imagenet.UnsupMetaMiniImageNet,
 'vl-meta-mini-imagenet': datasets.mini_imagenet.VLMetaMiniImageNet,
 'tiered-imagenet': datasets.tiered_imagenet.TieredImageNet,
 'meta-tiered-imagenet': datasets.tiered_imagenet.MetaTieredImageNet,
 'seq-meta-tiered-imagenet': datasets.tiered_imagenet.SeqMetaTieredImageNet,
 'cifar-fs': datasets.cifar100.CifarFS,
 'meta-cifar-fs': datasets.cifar100.MetaCifarFS,
 'fc100': datasets.cifar100.FC100,
 'meta-fc100': datasets.cifar100.MetaFC100,
 'cub200': datasets.cub200.CUB200,
 'meta-cub200': datasets.cub200.MetaCUB200,
 'inatural': datasets.inatural.INat2017,
 'meta-inatural': datasets.inatural.MetaINat2017,
 'omniglot': datasets.omniglot.Omniglot,
 'meta-omniglot': datasets.omniglot.MetaOmniglot,
 'meta-domain-net': datasets.domain_net.MetaDomainNet,
 'meta-mixed-set': datasets.mixset.mixedDatas

In [6]:
mixset = datasets.datasets['meta-mixed-set'](root_mini = '/srv/home/zxu444/datasets/mini-imagenet', 
                                             root_domain = '/srv/home/zxu444/datasets/domainNet/sketch_split',
                                             size = 224,
                                             transform = 'dinov2', val_transform = 'dinov2',
                                             n_way = 15)

mini-imagenet:  /srv/home/zxu444/datasets/mini-imagenet/miniImageNet_category_split_train_phase_train.pickle
/srv/home/zxu444/datasets/domainNet/sketch_split/train
start sampling part dataset
Loading labels from cached file /srv/home/zxu444/datasets/domainNet/sketch_split/cached_train_labels_domainNet.npy [took %.3f s] 0.0007951259613037109
construction dataset done!


In [7]:
shot, query, cats =  mixset[0]

In [8]:
shot.shape

torch.Size([1, 15, 1, 3, 224, 224])

In [9]:
query.shape

torch.Size([1, 225, 3, 224, 224])

In [10]:
mixset.n_way

15

In [11]:
cats

tensor([39,  6, 34, 54,  4, 28,  7, 27, 47, 57, 38, 49, 41, 25, 35])